version: '3.6'
services:
  send_current_month_report:
    build:
      context: .
    volumes:
      - ./sendmail.go:/sendmail.go
      - ./entrypoint.sh:/entrypoint.sh
    env_file:
    - vars.env
    entrypoint: >
      bash -c "/entrypoint.sh"
